# ########============================== ?ˆì—´ ?µì…˜ ==============================########

[preheat 60??
heat_bed: 60
[preheat 80??
heat_bed: 80
[preheat 100??
heat_bed: 100
[preheat 110??
heat_bed: 110

# ########============================== ?„í‚¹/?Œí‚¹ ==============================########

[menu __main ì¤€ë¹?
name: ì¤€ë¹?
icon: extruder

[menu __main ì¤€ë¹?T1]
name: T1
icon: extruder-1

[menu __main ì¤€ë¹?T1 temp]
name: ?¨ë„ ?•ì¸
icon: heat-up
panel: temperature

[menu __main ì¤€ë¹?T1 dock]
name: ?„í‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_0"}

[menu __main ì¤€ë¹?T1 park]
name: ?Œí‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_0"}

[menu __main ì¤€ë¹?T1 preheat]
name: ?¸ì¦ ?ˆì—´
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main ì¤€ë¹?T1 extrude]
name: ?•ì¶œ/?´ì¶œ
icon: extrude
panel: extrude

[menu __main ì¤€ë¹?T2]
name: T2
icon: extruder-2

[menu __main ì¤€ë¹?T2 temp]
name: ?¨ë„ ?•ì¸
icon: heat-up
panel: temperature

[menu __main ì¤€ë¹?T2 dock]
name: ?„í‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_1"}

[menu __main ì¤€ë¹?T2 park]
name: ?Œí‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_1"}

[menu __main ì¤€ë¹?T2 preheat]
name: ?¸ì¦ ?ˆì—´
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main ì¤€ë¹?T2 extrude]
name: ?•ì¶œ/?´ì¶œ
icon: extrude
panel: extrude

[menu __main ì¤€ë¹?T3]
name: T3
icon: extruder-3

[menu __main ì¤€ë¹?T3 temp]
name: ?¨ë„ ?•ì¸
icon: heat-up
panel: temperature

[menu __main ì¤€ë¹?T3 dock]
name: ?„í‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_2"}

[menu __main ì¤€ë¹?T3 park]
name: ?Œí‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_2"}

[menu __main ì¤€ë¹?T3 preheat]
name: ?¸ì¦ ?ˆì—´
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main ì¤€ë¹?T3 extrude]
name: ?•ì¶œ/?´ì¶œ
icon: extrude
panel: extrude

[menu __main ì¤€ë¹?T4]
name: T4
icon: extruder-4

[menu __main ì¤€ë¹?T4 temp]
name: ?¨ë„ ?•ì¸
icon: heat-up
panel: temperature

[menu __main ì¤€ë¹?T4 dock]
name: ?„í‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_3"}

[menu __main ì¤€ë¹?T4 park]
name: ?Œí‚¹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_3"}

[menu __main ì¤€ë¹?T4 preheat]
name: ?¸ì¦ ?ˆì—´
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main ì¤€ë¹?T4 extrude]
name: ?•ì¶œ/?´ì¶œ
icon: extrude
panel: extrude

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-darker
#~# confirm_estop = True
#~# show_heater_power = True
#~# show_scroll_steppers = True
#~# print_sort_dir = date_desc
#~# language = ko
#~#
