# ########============================== Bed Preheat Option ==============================########

[preheat 60℃]
heat_bed: 60
[preheat 80℃]
heat_bed: 80
[preheat 100℃]
heat_bed: 100
[preheat 110℃]
heat_bed: 110

# ########============================== Tool Head Prepare ==============================########

[menu __main 준비]
name: 준비
icon: extruder

[menu __main 준비 T1]
name: T1
icon: extruder-1

[menu __main 준비 T1 dock]
name: 도킹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_0"}

[menu __main 준비 T1 park]
name: 파킹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_0"}

[menu __main 준비 T1 temp]
name: 예열
icon: heat-up
panel: temperature

[menu __main 준비 T2]
name: T2
icon: extruder-2

[menu __main 준비 T2 dock]
name: 도킹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_1"}

[menu __main 준비 T2 park]
name: 파킹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_1"}

[menu __main 준비 T2 temp]
name: 예열
icon: heat-up
panel: temperature

[menu __main 준비 T3]
name: T3
icon: extruder-3

[menu __main 준비 T3 dock]
name: 도킹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_2"}

[menu __main 준비 T3 park]
name: 파킹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_2"}

[menu __main 준비 T3 temp]
name: 예열
icon: heat-up
panel: temperature

[menu __main 준비 T4]
name: T4
icon: extruder-4

[menu __main 준비 T4 dock]
name: 도킹
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_3"}

[menu __main 준비 T4 park]
name: 파킹
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_3"}

[menu __main 준비 T4 temp]
name: 예열
icon: heat-up
panel: temperature

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-darker
#~# confirm_estop = True
#~# show_heater_power = True
#~# print_sort_dir = date_desc
#~# language = ko
#~#
