# ########============================== 프린터 기능 설정 ==============================########

[printer FLEX4]
extrude_distances: 5, 10, 15, 20
extrude_speeds: 2, 5, 8, 12

[menu __main more limits]
enable: False

[menu __main more macros]
enable: False

[menu __main more pins]
enable: False

[menu __main more console]
enable: False

[menu __main more input_shaper]
enable: False

[menu __main more fine_tune]
enable: False

[menu __main more updater]
enable: False

[menu __main more camera]
enable: False

[menu __main more print_status]
name: 출력 화면
icon: printer
panel: job_status

[menu __main prepare_preview]
name: 준비
icon: extruder
panel: tool_prepare

# ########============================== 퀵 예열 ==============================########

[preheat Bed : 60℃]
#extruder: 230
heater_bed: 60
[preheat Bed : 80℃]
#extruder: 230
heater_bed: 80
[preheat Bed : 100℃]
#extruder: 230
heater_bed: 100
[preheat Bed : 110℃]
#extruder: 230
heater_bed: 110

# ########============================== 히터 테스트 ==============================########

[menu __main more heater_test]
name: 노즐 히터 테스트
icon: extruder

[menu __main more heater_test auto_test]
name: 자동 히터 테스트
icon: extruder
method: printer.gcode.script
params: {"script": "HEATER_TEST"}

[menu __main more heater_test heater_off]
name: 테스트 강제 종료
icon: cancel
method: printer.gcode.script
params: {"script": "HEATER_TEST_OFF"}

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-darker
#~# confirm_estop = True
#~# show_heater_power = True
#~# print_sort_dir = date_desc
#~# language = ko
#~#
