# ########============================== Printer Function Settings ==============================########

[printer FLEX4]
extrude_distances: 1, 5, 10, 25
extrude_speeds: 1, 2, 5, 10

[menu __main more limits]
enable: False

[menu __main more macros]
enable: False

[menu __main more pins]
enable: False

[menu __main more console]
enable: False

[menu __main more input_shaper]
enable: False

[menu __main more fine_tune]
enable: False

[menu __main more updater]
enable: False

[menu __main more camera]
enable: False

[menu __main more print_status]
name: Print Status
icon: printer
panel: job_status

[menu __main prepare_preview]
name: Prepare
icon: extruder
panel: tool_prepare

# ########============================== Quick Preheat ==============================########

[preheat Bed : 60℃]
#extruder: 230
heater_bed: 60

[preheat Bed : 80℃]
#extruder: 230
heater_bed: 80

[preheat Bed : 100℃]
#extruder: 230
heater_bed: 100

[preheat Bed : 110℃]
#extruder: 230
heater_bed: 110

# ########============================== Heater Test ==============================########

[menu __main more heater_test]
name: Nozzle Heater Test
icon: extruder

[menu __main more heater_test auto_test]
name: Automatic Heater Test
icon: extruder
method: printer.gcode.script
params: {"script": "HEATER_TEST"}

[menu __main more heater_test heater_off]
name: Stop Heater Test
icon: cancel
method: printer.gcode.script
params: {"script": "HEATER_TEST_OFF"}

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-darker
#~# confirm_estop = True
#~# show_heater_power = True
#~# print_sort_dir = date_desc
#~# language = en
#~#