# ########============================== Bed Preheat Option ==============================########

[preheat 60℃]
heat_bed: 60
[preheat 80℃]
heat_bed: 80
[preheat 100℃]
heat_bed: 100
[preheat 110℃]
heat_bed: 110

# ########============================== Tool Head Prepare ==============================########

[menu __main Prepare]
name: Prepare
icon: extruder

[menu __main Prepare T1]
name: T1
icon: extruder-1

[menu __main Prepare T1 temp]
name: Temperature
icon: heat-up
panel: temperature

[menu __main Prepare T1 dock]
name: Dock
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_0"}

[menu __main Prepare T1 park]
name: Park
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_0"}

[menu __main Prepare T1 preheat]
name: Nozzle Preheat
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main Prepare T1 extrude]
name: Extrude/Retract
icon: extrude
panel: extrude

[menu __main Prepare T2]
name: T2
icon: extruder-2

[menu __main Prepare T2 temp]
name: Temperature
icon: heat-up
panel: temperature

[menu __main Prepare T2 dock]
name: Dock
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_1"}

[menu __main Prepare T2 park]
name: Park
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_1"}

[menu __main Prepare T2 preheat]
name: Nozzle Preheat
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main Prepare T2 extrude]
name: Extrude/Retract
icon: extrude
panel: extrude

[menu __main Prepare T3]
name: T3
icon: extruder-3

[menu __main Prepare T3 temp]
name: Temperature
icon: heat-up
panel: temperature

[menu __main Prepare T3 dock]
name: Dock
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_2"}

[menu __main Prepare T3 park]
name: Park
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_2"}

[menu __main Prepare T3 preheat]
name: Nozzle Preheat
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main Prepare T3 extrude]
name: Extrude/Retract
icon: extrude
panel: extrude

[menu __main Prepare T4]
name: T4
icon: extruder-4

[menu __main Prepare T4 temp]
name: Temperature
icon: heat-up
panel: temperature

[menu __main Prepare T4 dock]
name: Dock
icon: shuffle
method: printer.gcode.script
params: {"script": "DOCK_3"}

[menu __main Prepare T4 park]
name: Park
icon: shuffle
method: printer.gcode.script
params: {"script": "PARK_3"}

[menu __main Prepare T4 preheat]
name: Nozzle Preheat
icon: heat-up
method: printer.gcode.script
params: {"script": "SET_HEATER_TEMPERATURE HEATER=extruder TARGET=250"}

[menu __main Prepare T4 extrude]
name: Extrude/Retract
icon: extrude
panel: extrude

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-darker
#~# confirm_estop = True
#~# show_heater_power = True
#~# show_scroll_steppers = True
#~# print_sort_dir = date_desc
#~# language = en
#~#
